// frontend/src/components/Dashboard.svelte
<script>
  import { auth, logout } from '../lib/auth.js';
  import { uploadFiles, apiRequest } from '../lib/api.js';
  import { Upload, LogOut, Link, Clock, Lock, FileText, Folder } from 'lucide-svelte';

  let files; // FileList
  let uploadResult = null; // Share Object
  let error = '';
  let shareSettings = {
      password: '',
      expires_minutes: 30
  };
  let shareUpdateMsg = '';
  let isLoading = false;

  async function handleUpload() {
    if (!files || files.length === 0) return;
    isLoading = true;
    try {
        uploadResult = await uploadFiles(files, $auth.token);
        error = '';
        shareSettings = { password: '', expires_minutes: 30 };
        shareUpdateMsg = '';
    } catch (e) {
        error = e.message;
        uploadResult = null;
    } finally {
        isLoading = false;
    }
  }

  async function updateShareSettings() {
      if (!uploadResult) return;
      isLoading = true;
      try {
          const body = {
              public_id: uploadResult.public_id,
              password: shareSettings.password ? shareSettings.password : null,
              expires_minutes: shareSettings.expires_minutes ? parseInt(shareSettings.expires_minutes) : null
          };
          
          await apiRequest(`/share/${uploadResult.public_id}`, 'POST', body, $auth.token);
          shareUpdateMsg = 'Settings updated successfully!';
      } catch (e) {
          shareUpdateMsg = 'Error updating settings: ' + e.message;
      } finally {
          isLoading = false;
      }
  }
</script>

<div class="min-h-screen bg-gray-100 dark:bg-zinc-900 p-8">
  <div class="max-w-4xl mx-auto space-y-8">
    
    <header class="flex justify-between items-center bg-white dark:bg-zinc-950 p-6 rounded-lg shadow-sm border border-zinc-200 dark:border-zinc-800">
      <div>
        <h1 class="text-2xl font-bold text-gray-900 dark:text-white">FileShare</h1>
        <p class="text-sm text-gray-500 dark:text-gray-400">Welcome back, {$auth.user.username}</p>
      </div>
      <button 
        on:click={logout}
        class="flex items-center gap-2 px-4 py-2 text-sm font-medium text-red-600 bg-red-50 rounded-lg hover:bg-red-100 dark:bg-red-900/10 dark:text-red-400 dark:hover:bg-red-900/20 transition-colors"
      >
        <LogOut size={16} />
        Logout
      </button>
    </header>

    <section class="bg-white dark:bg-zinc-950 p-6 rounded-lg shadow-sm border border-zinc-200 dark:border-zinc-800">
      <h2 class="text-xl font-semibold mb-4 flex items-center gap-2 dark:text-white">
        <Upload size={20} />
        Upload Files
      </h2>
      
      <div class="flex flex-col gap-4">
        <div class="flex items-center justify-center w-full">
            <label for="dropzone-file" class="flex flex-col items-center justify-center w-full h-64 border-2 border-gray-300 border-dashed rounded-lg cursor-pointer bg-gray-50 dark:hover:bg-zinc-800 dark:bg-zinc-900 hover:bg-gray-100 dark:border-gray-600 dark:hover:border-gray-500 transition-colors">
                <div class="flex flex-col items-center justify-center pt-5 pb-6 text-center">
                    <Folder class="w-12 h-12 mb-4 text-gray-400" />
                    {#if files && files.length > 0}
                         <p class="mb-2 text-sm text-gray-500 dark:text-gray-400 font-semibold">{files.length} file(s) selected</p>
                         <ul class="text-xs text-gray-400 max-h-32 overflow-y-auto">
                            {#each Array.from(files) as f}
                                <li>{f.name}</li>
                            {/each}
                         </ul>
                    {:else}
                        <p class="mb-2 text-sm text-gray-500 dark:text-gray-400"><span class="font-semibold">Click to upload</span> or drag and drop</p>
                        <p class="text-xs text-gray-500 dark:text-gray-400">Select multiple files at once</p>
                    {/if}
                </div>
                <!-- multiple attribute added -->
                <input id="dropzone-file" type="file" multiple class="hidden" on:change={e => files = e.target.files} />
            </label>
        </div> 

        {#if error}
            <div class="p-4 text-sm text-red-700 bg-red-100 rounded-lg dark:bg-red-900/50 dark:text-red-400">
                {error}
            </div>
        {/if}

        <button 
            on:click={handleUpload} 
            disabled={!files || isLoading}
            class="w-full text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
        >
            {isLoading ? 'Uploading...' : 'Upload Files'}
        </button>
      </div>
    </section>

    {#if uploadResult}
    <section class="bg-white dark:bg-zinc-950 p-6 rounded-lg shadow-sm border border-zinc-200 dark:border-zinc-800 animate-in fade-in slide-in-from-bottom-4 duration-500">
        <div class="mb-6 pb-6 border-b border-gray-100 dark:border-zinc-800">
            <h3 class="text-lg font-semibold text-green-600 dark:text-green-400 mb-2">Share Created!</h3>
            <div class="flex items-center gap-2 p-3 bg-gray-50 dark:bg-zinc-900 rounded-md border border-gray-200 dark:border-zinc-700 mb-4">
                <Link size={16} class="text-gray-500" />
                <a href={uploadResult.share_link} target="_blank" class="text-blue-600 hover:underline text-sm break-all">{uploadResult.share_link}</a>
            </div>

            <div class="bg-gray-50 dark:bg-zinc-900 p-4 rounded-md">
                <h4 class="text-sm font-semibold mb-2 text-gray-700 dark:text-gray-300">Files in this Share:</h4>
                <ul class="space-y-1">
                    {#each uploadResult.files as file}
                        <li class="flex items-center gap-2 text-sm text-gray-600 dark:text-gray-400">
                            <FileText size={14} /> {file.filename}
                        </li>
                    {/each}
                </ul>
            </div>
        </div>
        
        <div class="space-y-4">
            <h4 class="text-md font-medium dark:text-white">Share Settings</h4>
            
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                    <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white flex items-center gap-2">
                        <Lock size={16} /> Password Protection (Optional)
                    </label>
                    <input 
                        type="password" 
                        bind:value={shareSettings.password} 
                        placeholder="Set a password"
                        class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-zinc-900 dark:border-zinc-700 dark:placeholder-gray-400 dark:text-white"
                    />
                </div>
                <div>
                    <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white flex items-center gap-2">
                    <select 
                        bind:value={shareSettings.expires_minutes} 
                        class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-zinc-900 dark:border-zinc-700 dark:text-white"
                    >
                        <option value={5}>5 minutes</option>
                        <option value={15}>15 minutes</option>
                        <option value={30}>30 minutes</option>
                        <option value={60}>1 hour</option>
                        <option value={360}>6 hours</option>
                        <option value={720}>12 hours</option>
                        <option value={1440}>1 day</option>
                    </select>
                </div>
            </div>

            <button 
                on:click={updateShareSettings}
                disabled={isLoading}
                class="text-white bg-zinc-800 hover:bg-zinc-900 focus:ring-4 focus:ring-zinc-300 font-medium rounded-lg text-sm px-5 py-2.5 dark:bg-zinc-700 dark:hover:bg-zinc-600 dark:focus:ring-zinc-800 disabled:opacity-50 transition-colors"
            >
                {isLoading ? 'Saving...' : 'Save Settings'}
            </button>
            
            {#if shareUpdateMsg}
                <p class="text-sm mt-2 {shareUpdateMsg.includes('Error') ? 'text-red-500' : 'text-green-500'}">
                    {shareUpdateMsg}
                </p>
            {/if}
        </div>
    </section>
    {/if}

  </div>
</div>

// frontend/src/components/Dashboard.tsx
import { useState, useRef } from 'react'
import { useAuth } from '../hooks/useAuth'
import { uploadFiles, apiRequest, ApiError } from '../lib/api'
import { Button } from './ui/button'
import { Input } from './ui/input'
import { Label } from './ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select'
import { Alert, AlertDescription } from './ui/alert'
import { Upload, LogOut, Link, Clock, Lock, FileText, Folder } from 'lucide-react'

interface ShareResult {
  public_id: string;
  share_link: string;
  files: Array<{ filename: string }>;
}

export default function Dashboard() {
  const { user, token, logout, handleTokenExpiration } = useAuth()
  const fileInputRef = useRef<HTMLInputElement>(null)
  const [files, setFiles] = useState<FileList | null>(null)
  const [uploadResult, setUploadResult] = useState<ShareResult | null>(null)
  const [error, setError] = useState('')
  const [shareSettings, setShareSettings] = useState({
    password: '',
    expires_minutes: '30'
  })
  const [shareUpdateMsg, setShareUpdateMsg] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const [isUpdatingSettings, setIsUpdatingSettings] = useState(false)

  async function handleUpload() {
    if (!files || files.length === 0) return
    setIsLoading(true)
    try {
      const result = await uploadFiles(files, token!)
      setUploadResult(result)
      setError('')
      setShareSettings({ password: '', expires_minutes: '30' })
      setShareUpdateMsg('Files uploaded successfully!')
    } catch (e) {
      const error = e as ApiError
      if (error.isTokenExpired) {
        handleTokenExpiration()
      } else {
        setError(error instanceof Error ? error.message : 'Upload failed')
      }
      setUploadResult(null)
    } finally {
      setIsLoading(false)
    }
  }

  async function updateShareSettings() {
    if (!uploadResult) return
    setIsUpdatingSettings(true)
    try {
      const body = {
        public_id: uploadResult.public_id,
        password: shareSettings.password ? shareSettings.password : null,
        expires_minutes: shareSettings.expires_minutes ? parseInt(shareSettings.expires_minutes) : null
      }
      
      await apiRequest(`/share/${uploadResult.public_id}`, 'POST', body, token!)
      setShareUpdateMsg('Settings updated successfully!')
    } catch (e) {
      const error = e as ApiError
      if (error.isTokenExpired) {
        handleTokenExpiration()
      } else {
        setShareUpdateMsg('Error updating settings: ' + (error instanceof Error ? error.message : 'Unknown error'))
      }
    } finally {
      setIsUpdatingSettings(false)
    }
  }

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setFiles(e.target.files)
  }

  return (
    <div className="min-h-screen bg-gray-100 dark:bg-zinc-900 p-8">
      <div className="max-w-4xl mx-auto space-y-8">
        
        <header className="flex justify-between items-center bg-white dark:bg-zinc-950 p-6 rounded-lg shadow-sm border border-zinc-200 dark:border-zinc-800">
          <div>
            <h1 className="text-2xl font-bold text-gray-900 dark:text-white">FileShare</h1>
            <p className="text-sm text-gray-500 dark:text-gray-400">Welcome back, {user?.username}</p>
          </div>
          <Button 
            onClick={logout}
            variant="outline"
            className="flex items-center gap-2 text-red-600 hover:text-red-700"
          >
            <LogOut size={16} />
            Logout
          </Button>
        </header>

        <section className="bg-white dark:bg-zinc-950 p-6 rounded-lg shadow-sm border border-zinc-200 dark:border-zinc-800">
          <h2 className="text-xl font-semibold mb-4 flex items-center gap-2 dark:text-white">
            <Upload size={20} />
            Upload Files
          </h2>
          
          <div className="flex flex-col gap-4">
            <div className="flex items-center justify-center w-full">
              <label className="flex flex-col items-center justify-center w-full h-64 border-2 border-gray-300 border-dashed rounded-lg cursor-pointer bg-gray-50 dark:hover:bg-zinc-800 dark:bg-zinc-900 hover:bg-gray-100 dark:border-gray-600 dark:hover:border-gray-500 transition-colors">
                <div className="flex flex-col items-center justify-center pt-5 pb-6 text-center">
                  <Folder className="w-12 h-12 mb-4 text-gray-400" />
                  {files && files.length > 0 ? (
                    <>
                      <p className="mb-2 text-sm text-gray-500 dark:text-gray-400 font-semibold">{files.length} file(s) selected</p>
                      <ul className="text-xs text-gray-400 max-h-32 overflow-y-auto">
                        {Array.from(files).map((f, index) => (
                          <li key={index}>{f.name}</li>
                        ))}
                      </ul>
                    </>
                  ) : (
                    <>
                      <p className="mb-2 text-sm text-gray-500 dark:text-gray-400"><span className="font-semibold">Click to upload</span> or drag and drop</p>
                      <p className="text-xs text-gray-500 dark:text-gray-400">Select multiple files at once</p>
                    </>
                  )}
                </div>
                <input 
                  ref={fileInputRef}
                  type="file" 
                  multiple 
                  className="hidden" 
                  onChange={handleFileChange} 
                />
              </label>
            </div> 

            {error && (
              <Alert variant="destructive">
                <AlertDescription>{error}</AlertDescription>
              </Alert>
            )}

            <Button 
              onClick={handleUpload} 
              disabled={!files || isLoading}
              className="w-full relative"
            >
              {isLoading && (
                <div className="absolute inset-0 bg-background/50 rounded-md flex items-center justify-center">
                  <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-current mr-2"></div>
                </div>
              )}
              <span className={isLoading ? 'opacity-50' : ''}>
                {isLoading ? 'Uploading...' : 'Upload Files'}
              </span>
            </Button>
          </div>
        </section>

        {uploadResult && (
          <section className="bg-white dark:bg-zinc-950 p-6 rounded-lg shadow-sm border border-zinc-200 dark:border-zinc-800 animate-in fade-in slide-in-from-bottom-4 duration-500">
            <div className="mb-6 pb-6 border-b border-gray-100 dark:border-zinc-800">
              <h3 className="text-lg font-semibold text-green-600 dark:text-green-400 mb-2">Share Created!</h3>
              <div className="flex items-center gap-2 p-3 bg-gray-50 dark:bg-zinc-900 rounded-md border border-gray-200 dark:border-zinc-700 mb-4">
                <Link size={16} className="text-gray-500" />
                <a href={uploadResult.share_link} target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline text-sm break-all">{uploadResult.share_link}</a>
              </div>

              <div className="bg-gray-50 dark:bg-zinc-900 p-4 rounded-md">
                <h4 className="text-sm font-semibold mb-2 text-gray-700 dark:text-gray-300">Files in this Share:</h4>
                <ul className="space-y-1">
                  {uploadResult.files.map((file, index) => (
                    <li key={index} className="flex items-center gap-2 text-sm text-gray-600 dark:text-gray-400">
                      <FileText size={14} /> {file.filename}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
            
            <div className="space-y-4">
              <h4 className="text-md font-medium dark:text-white">Share Settings</h4>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label className="flex items-center gap-2">
                    <Lock size={16} /> Password Protection (Optional)
                  </Label>
                  <Input 
                    type="password" 
                    value={shareSettings.password}
                    onChange={(e) => setShareSettings(prev => ({ ...prev, password: e.target.value }))}
                    placeholder="Set a password"
                  />
                </div>
                <div className="space-y-2">
                  <Label className="flex items-center gap-2">
                    <Clock size={16} /> Expiration Time
                  </Label>
                  <Select 
                    value={shareSettings.expires_minutes}
                    onValueChange={(value) => setShareSettings(prev => ({ ...prev, expires_minutes: value }))}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="5">5 minutes</SelectItem>
                      <SelectItem value="15">15 minutes</SelectItem>
                      <SelectItem value="30">30 minutes</SelectItem>
                      <SelectItem value="60">1 hour</SelectItem>
                      <SelectItem value="360">6 hours</SelectItem>
                      <SelectItem value="720">12 hours</SelectItem>
                      <SelectItem value="1440">1 day</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <Button 
                onClick={updateShareSettings}
                disabled={isUpdatingSettings}
                variant="secondary"
                className="flex items-center gap-2 relative"
              >
                {isUpdatingSettings && (
                  <div className="absolute inset-0 bg-secondary/50 rounded-md flex items-center justify-center">
                    <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-current"></div>
                  </div>
                )}
                <span className={isUpdatingSettings ? 'opacity-50' : ''}>
                  {isUpdatingSettings ? 'Saving...' : 'Save Settings'}
                </span>
              </Button>
              
              {shareUpdateMsg && (
                <Alert className={shareUpdateMsg.includes('Error') ? 'border-red-200 bg-red-50 dark:border-red-800 dark:bg-red-950' : 'border-green-200 bg-green-50 dark:border-green-800 dark:bg-green-950'}>
                  <AlertDescription className={shareUpdateMsg.includes('Error') ? 'text-red-700 dark:text-red-300' : 'text-green-700 dark:text-green-300'}>
                    {shareUpdateMsg}
                  </AlertDescription>
                </Alert>
              )}
            </div>
          </section>
        )}

      </div>
    </div>
  )
}
